#import "/etc/utils.typ"

// Define glossary entry list
#let list = (
  (
    key: "visual_novel",
    short: "VN",
    long: "Visual Novel",
    plural: "VNs",
    description: "Eine Form von Interactive Fiction, welches zusätzlich audiovisuelle Elemente wie beispielsweise animierte Illustrationen verwendet.",
  ),
  (
    key: "interaktive_erzählung",
    short: "IE",
    long: "Interaktive Erzählung",
    plural: "IEs",
    description: "Eine Form von Erzählung, bei der der Handlungsverlauf nicht vorbestimmt ist. Nutzer*innen können je nach ihren Entscheidungen einen unterschiedlichen Handlungsverlauf erfahren.",
  ),
  (
    key: "if",
    short: "IF",
    long: "Interactive Fiction",
    plural: "IFs",
    description: "Ein textbasiertes Videospielgenre, bei dem Spieler*innen Einfluss auf die Handlung nehmen können.",
  ),
  (
    key: "cross_platform",
    short: "Cross-Platform",
    description: "Beschreibt Software, die auf mehreren Betriebssystemen lauffähig ist.",
  ),
  (
    key: "ssot",
    short: "SSOT",
    long: "Single Source of Truth",
    description: "Ein Konzept in Informationssystemen, welches besagt, dass Informationsmodelle so strukturiert sein sollen, dass sie nur an einem einzigen Ort bearbeitet werden. Dieser ist der 'einzige Ort der Wahrheit'.",
  ),
  (
    key: "dsl",
    short: "DSL",
    plural: "DSLs",
    long: "Domain-Specific Language",
    description: "Eine Programmiersprache, die speziell für eine bestimmte Anwendungsdomäne entwickelt wurde.",
  ),
  (
    key: "gpl",
    short: "GPL",
    plural: "GPLs",
    long: "General Purpose Language",
    description: "Eine Programmiersprache, die für eine breite Palette von Anwendungen geeignet ist.",
  ),
  (
    key: "library",
    short: "Bibliothek",
    plural: "Bibliotheken",
    long: "Programmbibliothek",
    description: "Eine Sammlung von Funktionen und Klassen, die Lösungen für thematisch zusammengehörenden Problemstellungen anbieten.",
  ),
  (
    key: "framework",
    short: "Framework",
    plural: "Frameworks",
    description: "Ein Software-Framework ist ein Programmiergerüst, innerhalb dessen eine Anwendung erstellt werden kann. Dieses gibt in der Regel eine Anwendungsarchitektur vor und unterscheidet sich von einer Bibliothek durch Inversion of Control (deutsch Steuerungsumkehr).",
  ),
  (
    key: "ioc",
    short: "IoC",
    long: "Inversion of Control",
    description: "Design-Prinzip der Software-Entwicklung, bei dem die Steuerungskontrolle von der Anwendung an eine externe Komponente (wie ein Framework) übergeben wird.",
  ),
  (
    key: "kite2",
    short: "KITE II",
    description: "Projekt zur Entwicklung einer KI-gestützten, gamifizierten Anwendung, die Gründerinnen dabei unterstützen soll, resilienter im Umgang mit diskriminierenden Erfahrungen im Gründungsprozess zu werden.",
  ),
  (
    key: "llm",
    short: "LLM",
    long: "Large Language Model",
    plural: "LLMs",
    description: "Ein großes Sprachmodell, das auf maschinellem Lernen basiert und in der Lage ist, menschenähnliche Texte zu generieren und zu verstehen.",
  ),
  (
    key: "twine",
    short: "Twine",
    description: "Ein Open-Source-Werkzeug zur Erstellung interaktiver Geschichten.",
  ),
  (
    key: "serious_game",
    short: "Serious Game",
    plural: "Serious Games",
    description: "Ein Spiel, das nicht primär zur Unterhaltung, sondern zur Vermittlung von Wissen oder Fähigkeiten entwickelt wurde.",
  ),
  (
    key: "gamification",
    short: "Gamification",
    description: "Die Anwendung spieltypischer Elemente in einem nicht-spielerischen Kontext, um die Nutzererfahrung zu verbessern und das Engagement zu erhöhen.",
  ),
  (
    key: "prompt_engineering",
    short: "Prompt Engineering",
    description: "Prozess der Strukturierung einer Anfrage an ein generatives KI-Modell mit dem Ziel der Optimierung der Ausgabequalität.",
  ),
  (
    key: "bias",
    short: "Bias",
    plural: "Biases",
    description: "Im Fachbereich der Psychologie (auch kognitive Verzerrung oder kognitiver Fehler genannt): Eine systematische Abweichung von Normen oder Rationalität im Urteil. Biases können zu Wahrnehmungsverzerrung, ungenaue Beurteilung oder Irrationalität führen.",
  ),
  (
    key: "immersion",
    short: "Immersion",
    description: "Im Fachbereich der Videospiele: die Wahrnehmung physisch präsent in einer nicht-physischen Welt zu sein.",
  ),
  (
    key: "gui",
    short: "GUI",
    plural: "GUIs",
    long: "Grafische Benutzeroberfläche",
    longplural: "Grafische Benutzeroberflächen",
    description: "Eine Art von Benutzerschnittstelle, die es Nutzer*innen ermöglicht, mit Computern über visuelle Elemente zu interagieren.",
  ),
  (
    key: "bga",
    short: "BGA",
    long: "Bundesweite Gründerinnenagentur",
    description: "Ein deutschlandweites Kompetenz- und Servicezentrum zur unternehmerischen Selbstständigkeit von Frauen.",
  ),
  (
    key: "kite",
    short: "KITE",
    long: "KI Thinktank female Entrepreneurship",
    description: "Projekt der BGA zur Diskriminierungs-Bekämpfung für Gründerinnen durch gezielten Kompetenzaufbau beim Erkennen und Bewältigen von Diskriminierungsmustern.",
  ),
  (
    key: "scene",
    short: "Szene",
    plural: "Szenen",
    description: "In der Spiele-Entwicklung: Ein Bereich oder Abschnitt eines Spiels, der eine bestimmte Handlung oder Umgebung darstellt. Szenen können verschiedene Assets wie Charaktere, Objekte und Hintergründe enthalten.",
  ),
  (
    key: "asset",
    short: "Asset",
    plural: "Assets",
    description: "In der Spiele-Entwicklung: Eine Datei, die in einer Anwendung verwendet wird, wie zum Beispiel Bilder, Audio-Dateien, 3D-Modelle, Texturen oder Skripte.",
  ),
  (
    key: "sprite",
    short: "Sprite",
    plural: "Sprites",
    description: "In der Spiele-Entwicklung: Eine zweidimensionale Bitmap, die Teil einer größeren Szene ist. Meist in Verbindung mit zweidimensionalen Spielen verwendet.",
  ),
  (
    key: "ea",
    short: "endlicher Automat",
    description: "Modelliert ein Verhalten mit einer endlichen Menge von Zuständen und Zustandsübergängen.",
  ),
  (
    key: "json",
    short: "JSON",
    long: "JavaScript Object Notation",
    description: "Ein kompaktes Datenformat in lesbarer Textform für den Datenaustausch zwischen Anwendungen.",
  ),
  (
    key: "kmp",
    short: "KMP",
    long: "Kotlin Multiplatform",
    description: "Ein Kotlin Cross-Platform Entwicklungs-Framework, welches von JetBrains entwickelt wird.",
  ),
  (
    key: "cmp",
    short: "CMP",
    long: "Compose Multiplatform",
    description: "Ein deklaratives Cross-Platform UI Framework für Kotlin, welches auf Kotlin Multiplatform und Jetpack Compose basiert und von JetBrains entwickelt wird.",
  ),
  (
    key: "jc",
    short: "Jetpack Compose",
    description: "Ein deklaratives UI Framework für Android, welches von Google entwickelt wird.",
  ),
  (
    key: "di",
    short: "DI",
    long: "Dependency Injection",
    description: "Ein Software Entwurfsmuster, bei dem ein Objekt seine erforderlichen Abhängigkeiten aus einer externen Quelle bezieht, anstatt sie intern zu konstruieren.",
  ),
  (
    key: "singleton",
    short: "Singleton",
    description: "Ein Software Entwurfsmuster, bei der von einer gegebenen Klasse nur genau eine Instanz existieren kann.",
  ),
  (
    key: "factory",
    short: "Factory-Methode",
    plural: "Factory-Methoden",
    description: "Ein Software Entwurfsmuster, bei der die Konstruktion eines Objektes in eine externe Method ausgelagert wird.",
  ),
  (
    key: "mvvm",
    short: "MVVM",
    long: "Model-View-ViewModel",
    description: "Ein Architekturmuster, welches eine Anwendung in drei Arten von Komponenten unterteilt: das Model (Daten und Geschäftslogik), die View (Benutzeroberfläche) und das ViewModel (Vermittler zwischen Model und View).",
  ),
  (
    key: "ecs",
    short: "ECS",
    long: "Entity Component System",
    description: "Ein Architekturmuster, welches aus Entitäten besteht, die über bestimmten Komponenten von Daten verfügen. Die sogenannten Systeme manipulieren wiederum die Komponenten. Dieses wird häufig in der Videospiel-Entwicklung zur Repräsentation der Spielwelt-Objekte genutzt.",
  ),
)
